import type { Metadata } from 'next'
import { GlobalProvider } from '@/lib/context/store'
import { Providers } from '@/lib/utils/themeMode'
import './globals.css'
import { auth } from '@/lib/auth'
import { SessionProvider } from 'next-auth/react'
import HTMLayout from '@/components/organism/HTMLayout'
import { DarkLightContextProvider } from '@/lib/context/DarkLightContext'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  let session = await auth();
  console.log(session)

  return (
    <SessionProvider session={session}>
      <DarkLightContextProvider>
        <HTMLayout session={session} >
            {children}
        </HTMLayout>
      </DarkLightContextProvider>
    </SessionProvider>
  )
}
