import localFont from 'next/font/local'

export const work_Sans = localFont({
    src: [
      {
        path:'../public/fonts/WorkSans/WorkSans-Regular.ttf',
        weight:'400',
        style:'normal',
      },
      {
        path:'../public/fonts/WorkSans/WorkSans-Italic.ttf',
        weight:'400',
        style:'italic',
      },
      {
        path:'../public/fonts/WorkSans/WorkSans-Medium.ttf',
        weight:'500',
        style:'normal',
      },
      {
        path:'../public/fonts/WorkSans/WorkSans-MediumItalic.ttf',
        weight:'500',
        style:'italic',
      },
      {
        path:'../public/fonts/WorkSans/WorkSans-SemiBold.ttf',
        weight:'600',
        style:'normal',
      },
      {
        path:'../public/fonts/WorkSans/WorkSans-SemiBoldItalic.ttf',
        weight:'600',
        style:'italic',
      },
      {
        path:'../public/fonts/WorkSans/WorkSans-Bold.ttf',
        weight:'700',
        style:'normal',
      },
      {
        path:'../public/fonts/WorkSans/WorkSans-BoldItalic.ttf',
        weight:'700',
        style:'italic',
      }
    ],
    display:'swap',
    variable: '--font-work-sans'
  })

export const Jakarta_Sans = localFont({
    src: [
      {
        path:'../public/fonts/PlusJakartaSans/PlusJakartaSans-Regular.ttf',
        weight:'400',
        style:'normal',
      },
      {
        path:'../public/fonts/PlusJakartaSans/PlusJakartaSans-Italic.ttf',
        weight:'400',
        style:'italic',
      },
      {
        path:'../public/fonts/PlusJakartaSans/PlusJakartaSans-Medium.ttf',
        weight:'500',
        style:'normal',
      },
      {
        path:'../public/fonts/PlusJakartaSans/PlusJakartaSans-MediumItalic.ttf',
        weight:'500',
        style:'italic',
      },
      {
        path:'../public/fonts/PlusJakartaSans/PlusJakartaSans-SemiBold.ttf',
        weight:'600',
        style:'normal',
      },
      {
        path:'../public/fonts/PlusJakartaSans/PlusJakartaSans-SemiBoldItalic.ttf',
        weight:'600',
        style:'italic',
      },
      {
        path:'../public/fonts/PlusJakartaSans/PlusJakartaSans-Bold.ttf',
        weight:'700',
        style:'normal',
      },
      {
        path:'../public/fonts/PlusJakartaSans/PlusJakartaSans-BoldItalic.ttf',
        weight:'700',
        style:'italic',
      }
    ],
    display:'swap',
    variable: '--font-plus-jakarta-sans'
  })

export const source_Serif_Pro = localFont({
    src: [
      {
        path:'../public/fonts/SourceSerif4/SourceSerif4-Light.ttf',
        weight:'200',
        style:'normal',
      },
      {
        path:'../public/fonts/SourceSerif4/SourceSerif4-LightItalic.ttf',
        weight:'200',
        style:'italic',
      },
      {
        path:'../public/fonts/SourceSerif4/SourceSerif4-ExtraLight.ttf',
        weight:'300',
        style:'normal',
      },
      {
        path:'../public/fonts/SourceSerif4/SourceSerif4-ExtraLightItalic.ttf',
        weight:'300',
        style:'italic',
      },
      {
        path:'../public/fonts/SourceSerif4/SourceSerif4-Regular.ttf',
        weight:'400',
        style:'normal',
      },
      {
        path:'../public/fonts/SourceSerif4/SourceSerif4-Italic.ttf',
        weight:'400',
        style:'italic',
      },
      {
        path:'../public/fonts/SourceSerif4/SourceSerif4-SemiBold.ttf',
        weight:'600',
        style:'normal',
      },
      {
        path:'../public/fonts/SourceSerif4/SourceSerif4-SemiBoldItalic.ttf',
        weight:'600',
        style:'italic',
      },
      {
        path:'../public/fonts/SourceSerif4/SourceSerif4-Bold.ttf',
        weight:'700',
        style:'normal',
      },
      {
        path:'../public/fonts/PlusJakartaSans/PlusJakartaSans-BoldItalic.ttf',
        weight:'700',
        style:'italic',
      }
    ],
    display:'swap',
    variable: '--font-source-serif-pro'
  })
  